baseURL: 'https://disclaimerwarning.wilder.wp.computer/'
title: (ðœ”Ã—ð›¼) â¦§ð˜–â€‘ð˜– âŒ– [Wilder WPC] â˜® WARNING

# Uncomment when not installing with Hugo Modules
# theme: eureka
# Comment when not installing with Hugo Modules
theme: wangchucheng.com/hugo-eureka
# If you cannot access the Github mirror, you can also use the Gitee mirror: gitee.com/wangchucheng/hugo-eureka

paginate: 20
copyright: >
  &copy; 2025 The Wilder-ness Adventures & Wilder WPC & World Peacebrain Mindeye V1 ~ <a href="https://www.patreon.com/c/wilderwpc">Content Portal, Patreon (click)</a> ~ <a href="https://drive.google.com/file/d/13of5dva-mwCZr3u4rC9mIvp87TjA7qLz/view?usp=sharing"> ORIGIN STORY: A Study In Peace (Operator's Manual for the Timespace Matter Mindmachine)</a>
enableGitInfo: false
summaryLength: 75

defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir: false

# Uncomment for google analytics
# googleAnalytics: UA-123-45

markup:
  # Do not modify markup.highlight
  highlight:
    codeFences: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: always
